-- Insert a set of records.
INSERT INTO department (name) VALUES ("Back Office");
INSERT INTO department (name) VALUES ("Software");
INSERT INTO department (name) VALUES ("Support");
INSERT INTO department (name) VALUES ("Kitchen");
INSERT INTO role (title, salary, dept_id) VALUES ("CEO", 21032, 1);
INSERT INTO role (title, salary, dept_id) VALUES ("CTO", 1171, 1);
INSERT INTO role (title, salary, dept_id) VALUES ("Dev, sr", 25, 2);
INSERT INTO role (title, salary, dept_id) VALUES ("Dev, jr", 23, 2);
INSERT INTO role (title, salary, dept_id) VALUES ("Dev 1", 13, 3);
INSERT INTO role (title, salary, dept_id) VALUES ("Dev 2", 11, 3);
INSERT INTO role (title, salary, dept_id) VALUES ("Cook but better", 35, 4);
INSERT INTO role (title, salary, dept_id) VALUES ("Cook but average", 14, 4);
INSERT INTO role (title, salary, dept_id) VALUES ("Cook but worse", 7, 4);
INSERT INTO role (title, salary, dept_id) VALUES ("Coffee Bloke", 1, 4);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("John", "Doe", 1,1);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Mike", "Chan", 2, 1);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Ashley", "Rodrigeuz", 3, 2);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Kevin", "Tupik", 4, 3);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Malia", "Brown", 4, 3);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Sarah", "Lourd", 4, 3);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Tom", "Allen", 5, 2);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Christian", "Eckenrode", 6, 7);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("John", "Doe", 6, 7);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Mike", "Chan", 7, 2);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Ashley", "Rodrigeuz", 8, 10);
